SCREEN 9
PSET (x +  0 , y +  0 ),  8 
PSET (x +  0 , y +  1 ),  7 
PSET (x +  1 , y +  0 ),  7 
PSET (x +  1 , y +  1 ),  8 
PSET (x +  1 , y +  2 ),  7 
LINE (x +  1 , y + 3 )-(x +  4 , y +  3 ),  13 
PSET (x +  2 , y +  1 ),  6 
PSET (x +  2 , y +  2 ),  8 
LINE (x +  2 , y + 4 )-(x +  3 , y +  4 ),  13 
PSET (x +  3 , y +  1 ),  14 
LINE (x +  3 , y +  2 )-(x +  3 , y +  5 ),  13 
PSET (x +  4 , y +  1 ),  7 
PSET (x +  4 , y +  2 ),  14 
PSET (x +  4 , y +  4 ),  8 
LINE (x +  4 , y +  5 )-(x +  4 , y +  6 ),  13 
PSET (x +  5 , y +  2 ),  7 
PSET (x +  5 , y +  3 ),  14 
PSET (x +  5 , y +  4 ),  13 
PSET (x +  5 , y +  5 ),  8 
LINE (x +  5 , y +  6 )-(x +  5 , y +  7 ),  13 
PSET (x +  6 , y +  3 ),  7 
PSET (x +  6 , y +  4 ),  14 
PSET (x +  6 , y +  5 ),  13 
PSET (x +  6 , y +  6 ),  8 
LINE (x +  6 , y +  7 )-(x +  6 , y +  8 ),  13 
PSET (x +  7 , y +  4 ),  7 
PSET (x +  7 , y +  5 ),  14 
PSET (x +  7 , y +  6 ),  13 
PSET (x +  7 , y +  7 ),  8 
LINE (x +  7 , y +  8 )-(x +  7 , y +  9 ),  13 
PSET (x +  8 , y +  5 ),  7 
PSET (x +  8 , y +  6 ),  14 
PSET (x +  8 , y +  7 ),  13 
PSET (x +  8 , y +  8 ),  8 
LINE (x +  8 , y +  9 )-(x +  8 , y +  10 ),  13 
PSET (x +  9 , y +  6 ),  7 
PSET (x +  9 , y +  7 ),  14 
PSET (x +  9 , y +  8 ),  13 
PSET (x +  9 , y +  9 ),  8 
LINE (x +  9 , y +  10 )-(x +  9 , y +  11 ),  13 
PSET (x +  10 , y +  7 ),  7 
PSET (x +  10 , y +  8 ),  14 
PSET (x +  10 , y +  9 ),  13 
PSET (x +  10 , y +  10 ),  8 
PSET (x +  10 , y +  11 ),  13 
PSET (x +  11 , y +  8 ),  7 
PSET (x +  11 , y +  9 ),  14 
PSET (x +  11 , y +  10 ),  13 
PSET (x +  12 , y +  9 ),  7 
