SCREEN 9
COLOR 0, 63
x = 300
y = 100
LINE (x + 0, y + 7)-(x + 0, y + 11), 8
LINE (x + 1, y + 5)-(x + 1, y + 6), 8
LINE (x + 1, y + 7)-(x + 1, y + 11), 10
LINE (x + 1, y + 12)-(x + 1, y + 13), 8
PSET (x + 2, y + 4), 8
LINE (x + 2, y + 5)-(x + 2, y + 6), 10
LINE (x + 2, y + 7)-(x + 2, y + 11), 14
LINE (x + 2, y + 12)-(x + 2, y + 13), 10
PSET (x + 2, y + 14), 8
LINE (x + 3, y + 3)-(x + 4, y + 3), 8
PSET (x + 3, y + 4), 10
LINE (x + 3, y + 5)-(x + 3, y + 13), 14
PSET (x + 3, y + 14), 12
LINE (x + 3, y + 15)-(x + 4, y + 15), 8
LINE (x + 4, y + 4)-(x + 4, y + 14), 14
LINE (x + 5, y + 2)-(x + 9, y + 2), 8
LINE (x + 5, y + 3)-(x + 8, y + 3), 10
LINE (x + 5, y + 4)-(x + 5, y + 14), 14
LINE (x + 5, y + 15)-(x + 9, y + 15), 12
LINE (x + 5, y + 16)-(x + 9, y + 16), 8
LINE (x + 6, y + 4)-(x + 6, y + 14), 14
LINE (x + 7, y + 4)-(x + 7, y + 9), 8
LINE (x + 7, y + 10)-(x + 12, y + 10), 14
LINE (x + 7, y + 11)-(x + 12, y + 11), 14
LINE (x + 7, y + 12)-(x + 11, y + 12), 14
LINE (x + 7, y + 13)-(x + 11, y + 13), 14
LINE (x + 7, y + 14)-(x + 9, y + 14), 14
LINE (x + 8, y + 4)-(x + 8, y + 8), 14
LINE (x + 8, y + 9)-(x + 10, y + 9), 8 '<---- Zeiger...
PSET (x + 9, y + 3), 12
LINE (x + 9, y + 4)-(x + 9, y + 8), 14
LINE (x + 10, y + 3)-(x + 11, y + 3), 8
LINE (x + 10, y + 4)-(x + 10, y + 8), 14
LINE (x + 10, y + 14)-(x + 11, y + 14), 12
LINE (x + 10, y + 15)-(x + 11, y + 15), 8
PSET (x + 11, y + 4), 12
LINE (x + 11, y + 5)-(x + 11, y + 13), 14
PSET (x + 12, y + 4), 8
PSET (x + 12, y + 5), 12
LINE (x + 12, y + 6)-(x + 12, y + 11), 14
LINE (x + 12, y + 12)-(x + 12, y + 13), 12
PSET (x + 12, y + 14), 8
LINE (x + 13, y + 5)-(x + 13, y + 6), 8
LINE (x + 13, y + 7)-(x + 13, y + 11), 12
LINE (x + 13, y + 12)-(x + 13, y + 13), 8
LINE (x + 14, y + 7)-(x + 14, y + 11), 8

