LINE ( 50 , 77 )-( 50 , 79 ),  8 
SLEEP
PSET ( 51 , 77 ),  8 
SLEEP
LINE ( 51 , 78 )-( 51 , 79 ),  15 
SLEEP
LINE ( 51 , 80 )-( 51 , 81 ),  8 
SLEEP
PSET ( 52 , 78 ),  8 
SLEEP
LINE ( 52 , 79 )-( 52 , 81 ),  15 
SLEEP
LINE ( 52 , 82 )-( 52 , 83 ),  8 
SLEEP
LINE ( 53 , 79 )-( 54 , 79 ),  8 
SLEEP
LINE ( 53 , 80 )-( 53 , 83 ),  15 
SLEEP
LINE ( 53 , 84 )-( 53 , 85 ),  8 
SLEEP
LINE ( 54 , 71 )-( 54 , 81 ),  8 
SLEEP
LINE ( 54 , 82 )-( 60 , 82 ),  15 
SLEEP
LINE ( 54 , 83 )-( 60 , 83 ),  15 
SLEEP
LINE ( 54 , 84 )-( 59 , 84 ),  15 
SLEEP
LINE ( 54 , 85 )-( 59 , 85 ),  15 
SLEEP
LINE ( 54 , 86 )-( 59 , 86 ),  8 
SLEEP
PSET ( 55 , 70 ),  8 
SLEEP
LINE ( 55 , 71 )-( 55 , 85 ),  15 
SLEEP
LINE ( 55 , 87 )-( 58 , 87 ),  8 
SLEEP
LINE ( 56 , 71 )-( 56 , 77 ),  8 
SLEEP
LINE ( 56 , 78 )-( 56 , 85 ),  15 
SLEEP
PSET ( 57 , 74 ),  8 
SLEEP
LINE ( 57 , 75 )-( 57 , 85 ),  15 
SLEEP
LINE ( 58 , 75 )-( 58 , 77 ),  8 
SLEEP
LINE ( 58 , 78 )-( 58 , 85 ),  15 
SLEEP
PSET ( 59 , 75 ),  8 
SLEEP
LINE ( 59 , 76 )-( 59 , 85 ),  15 
SLEEP
LINE ( 60 , 76 )-( 60 , 78 ),  8 
SLEEP
LINE ( 60 , 79 )-( 60 , 83 ),  15 
SLEEP
LINE ( 60 , 84 )-( 60 , 85 ),  8 
SLEEP
PSET ( 61 , 76 ),  8 
SLEEP
LINE ( 61 , 77 )-( 61 , 81 ),  15 
SLEEP
LINE ( 61 , 82 )-( 61 , 83 ),  8 
SLEEP
LINE ( 62 , 77 )-( 62 , 81 ),  8 
SLEEP
